### ISSUE TITLE
Support for Post Description

### ISSUE THREAD

**Issue by cjmetacrawler** [dudaster/ele-custom-skin#13]
It is much better if the Post Description is also available in creating Loop Templates. The only available option we have is the Post Summary which streip off all the HTML tags.

**Comment by HmCody** [comment]
I somehow accidentally inserted the Edit Post Content widget that is available when designing a Single Post  template into a Loop and it seems to give the full, formatted post content within the loop. I don't know how I did it the first time, but I managed to replicate it by creating a single post template, inserting and then copying a Post Content widget, then pasting it into my loop template.  

My only concern is that since it is not actually available in the widgets list, it may eventually **stop** working. If one of the plugin developers could address this, I would really appreciate it!

**Comment by cjmetacrawler** [comment]
The only option we have right now is doing that and by removing the "strip off html tags" functionality of Wordpress for excerpt in Functions.php

**Comment by roiko** [comment]
Is there any update on this issue?
I temporarily solved the problem by adding a Custom Field of type WYSIWYG to my post with ACF. Then I changed the source of the text widget to the just added dield.
WYSIWYG field allows you to format the text, and this information is read in loop template

**Comment by dudaster** [comment]
use post content widget!
