### ISSUE TITLE
Pagination bug with ajax filter

### ISSUE THREAD

**Issue by clement-menard** [dudaster/ele-custom-skin#487]
Hi,

Our website use Elementor Pro + ECS + Search & Filter Pro.

On our archive posts page, we use Search & Filter Pro to filter posts with ajax fields. When we use the "Search field" (input field), everything works. But when we use "Category" or "Tag" filters (select fields), our pagination is broken, the ECS "Infinite Loading" animation appear but don't works.

**Original pagination**
<img width="1680" alt="Capture d’écran 2021-04-30 à 12 18 11" src="https://user-images.githubusercontent.com/9642015/116682165-2e3bb280-a9ae-11eb-95b6-3b11c31cad2b.png">

**Broken pagination**
<img width="1680" alt="Capture d’écran 2021-04-30 à 12 16 28" src="https://user-images.githubusercontent.com/9642015/116681961-ed439e00-a9ad-11eb-9366-30128fb9e61d.png">

How to resolve this ?

=> https://link.infini.fr/K2WkpHhs

**Comment by dudaster** [comment]
You need to use the pagination of the filter if it has one.

The issue happens because the JavaScript Query Var ( ecs_ajax_params.posts ) is not changed when you select a filter through AJAX.

` ecs_ajax_params.posts` contains the wp_query of the loaded page and when you use AJAX it stays the same. You need to talk with the devs of the Filter Pro if there is a way to get the current query after ajax request and if there is a hook on ajax load.

Let me know what their answer is!
