### ISSUE TITLE
Same height no longer working after Elementor upgrade

### ISSUE THREAD

**Issue by BlackSheep42** [dudaster/ele-custom-skin#685]
Since updating to Elementor 3.5.5 and/or Elementor Pro 3.6.0 the Same Height function has stopped working.

**Comment by css31** [comment]
Hi,
I intend to buy the pro version, because I need the feature that allows to have the same height for the images in the gallery.
Can you tell if this will be fixed soon?

**Comment by css31** [comment]
Hi,
It seems that there is a workaround by setting the image height to VH.
Edit: not completely operational.

**Comment by marjoleinvandenbusken** [comment]
Same issue here, When can this be fixt?

**Comment by BlackSheep42** [comment]
Hi 
I did a roll back on Elementor Pro from 3.6.1 to 3.5.2 and it fixed the same height issue. Updated back to 3.6.1 and the problem came back. Any rollback on the base Elementor install made no difference.

**Comment by dudaster** [comment]
A fix would be available soon

**Comment by BlackSheep42** [comment]
That's great. Thanks for the update.

**Comment by umm-wdc** [comment]
@dudaster  any update on this ?

**Comment by davidofchatham** [comment]
Hoping there will be a fix on this soon!

**Comment by djaysan** [comment]
Hi! when equal height is enabled, using inner sections within the loop breaks the layout.

Thanks to @mmcgowan1 
I've discovered that if you have an inner section within the loop -- in my case to display two columns -- it breaks the post display, if "equal height" is turned on. The feature works if there is only one section in the post loop. This is a change in behavior because it worked fine with inner sections before.
