### ISSUE TITLE
Equal Height Stopped Working

### ISSUE THREAD

**Issue by KingGrizzly** [dudaster/ele-custom-skin#692]
Heads up: I'm up to date on Elementor Pro (3.6.1)/Elementor (3.5.5) and Wordpress. The equal height option has stopped working: 
<img width="1152" alt="image" src="https://user-images.githubusercontent.com/48737505/153295835-f915f574-1ad5-4ed4-9b79-ec6eb930e153.png">
Thanks.

**Comment by marjoleinvandenbusken** [comment]
Hi had the same issue, try the following custom css;

/* Fix - Elementor Custom Skin Equal Height */ .ecs-post-loop .elementor > .elementor-section {height:100%}

**Comment by KingGrizzly** [comment]
@marjoleinvandenbusken Thanks. I did something similar but may have instances where I don't want that to happen as well.

**Comment by BlackSheep42** [comment]
Hi.

I have the same issue. Posted earlier here: https://github.com/dudaster/ele-custom-skin/issues/685#issue-1126083225. As a test I rolled back to Elementor Pro to 3.5.2 and it fixed the issue.

Still waiting to find out when I permanent fix will be issued.

**Comment by mmcgowan1** [comment]
The fix just released for this issue works for me on some pages, but on one particular turning on "equal height" breaks the display of the page so that many parts of the posts don't display or are displayed on top of each other. I use Advanced Custom fields in these posts, so perhaps there is some interaction. In any case, the fix is a disaster. I need to turn off the feature so at least the page is readable.

**Comment by KingGrizzly** [comment]
The changelog says it is necessary to toggle equal height off and on for it to work properly again.

This means I have to hunt through every client site for every instance of equal height post listings. Say it ain’t so!

**Comment by mmcgowan1** [comment]
I've discovered that if you have an inner section within the loop -- in my case to display two columns -- it breaks the post display, if "equal height" is turned on. The feature works if there is only one section in the post loop. This is a change in behavior because it worked fine with inner sections before.

**Comment by KingGrizzly** [comment]
This impacts quite a few client sites, hoping there is a resolution possible?

**Comment by djaysan** [comment]
> I've discovered that if you have an inner section within the loop -- in my case to display two columns -- it breaks the post display, if "equal height" is turned on. The feature works if there is only one section in the post loop. This is a change in behavior because it worked fine with inner sections before.

It worked thank you!

**Comment by KingGrizzly** [comment]
I can confirm any of my Ele Custom Skins with an inner section in them break when Equal Heights is turned on. Any chance this can be resolved? Certain designs need the inner sections in order to work.

**Comment by KingGrizzly** [comment]
It's now mid-April and I still get the height issue but have discovered a clue: the 100% height feature works IF "make entire post a link?" is unselected. If I turn this feature on, the 100% height behavior doesn't always work but it will work if turned off.

So I've resorted to turning this off everywhere and writing some JS which makes the loop skin inherit the URL of a child link. 

Hopefully this clue helps the developer fix the issue. This is such a powerful and useful tool.
