### ISSUE TITLE
Slider Issue - Posts Running off the page

### ISSUE THREAD

**Issue by nelson-designs** [dudaster/ele-custom-skin#933]
When activating the slider option in Elementor, my posts run off of the page. On the front end it's also difficult to navigate through the slides creating a jumpy/skip action and then eventually resetting to be off the page. I can just see the last bit of the last slide on the left side. 

![image](https://github.com/dudaster/ele-custom-skin/assets/75410061/8a9ebef1-0b7e-47da-926e-fde8b64bcc79)

**How it should display (Removed the overflow Hidden to see this result):**

![image](https://github.com/dudaster/ele-custom-skin/assets/75410061/8c0c3791-ee43-48f8-a153-93bb7c43e447)

Thanks!

**Comment by youssefsanati** [comment]
I have the same problem! https://chefofpersia.de/
<img width="2554" alt="Bildschirmfoto 2024-03-18 um 15 24 54" src="https://github.com/dudaster/ele-custom-skin/assets/105479356/6bc5a71d-cfde-4c6e-9414-4894dfee96ca">

**Comment by bartistiek** [comment]
For everyone having this issue. Elementor pro has the same functionality now. 

1. Go to the original loop you have created in Ele Custom Skin (elementor theme builder -> loop). 
2. Copy the main section of the loop you have created. 
3. Go back to the main page of the elementor theme builder. 
4. Go to "Loop item" at the bottom of the menu. 
5. Create a new loop item and paste the section you have just created. 
6. Close the loop item and rename to a name you can remember. 
7. In the page where you have the issue go to the Posts item you had (see which custom posts where queried and what other ordering or selection criteria where set. Write these down or make screenshots
8. Remove the Posts element
9. Insert the "Loop Carousel" item
10. Choose the loop themplate you have just created as the template
11. Set the selection criteria like you had them before in the Posts element

You have now implemented a more structural solution and over time (when you have replaced all loopts) you can get rid of Elementor Custom Skin (since this plugin seems to be abandonned)
